#!/usr/bin/env bash
# This script displays all listening TCP and UDP ports along with the PID and program name
# -t: Show TCP ports
# -u: Show UDP ports
# -n: Show numerical addresses instead of resolving hostnames
# -l: Show only listening sockets
# -p: Show the PID and program name for each socket
# grep LISTEN: Filters the output to display only sockets that are in the "LISTEN" state


netstat -tunlp | grep LISTEN

